#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "This is a linux machine."

	sudo passwd root
	sudo passwd fox
	sudo apt-get update

	if ! command -v zsh &>/dev/null; then
		echo "Zsh is not installed. Installing..."
		sudo apt-get install zsh -y
		chsh -s "$(which zsh)"
	else
		echo "Zsh is already installed."
	fi

	sudo apt-get install git build-essential ripgrep pip nvim

	ln -s ~/dotfiles/.zprofile ~/.zprofile
	ln -s ~/dotfiles/.zshrc ~/.zshrc
	ln -s ~/dotfiles/.zsh ~/.zsh

	mkdir ~/.config
	ln -s ~/dotfiles/.config/nvim ~/.config/nvim

	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
