#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "This is a linux machine."

	sudo passwd root
	sudo passwd fox
	sudo apt-get update

	if ! command -v zsh &>/dev/null; then
		echo "Zsh is not installed. Installing..."
		sudo apt-get install zsh -y
		chsh -s "$(which zsh)"
	else
		echo "Zsh is already installed."
	fi

	sudo apt-get install git build-essential ripgrep pip neovim libssl-dev

	wget https://github.com/neovim/neovim/releases/download/v0.11.1/nvim-linux-x86_64.tar.gz
	tar xzf nvim-linux64.tar.gz
	sudo mv nvim-linux64 /usr/local/
	sudo ln -s /usr/local/nvim-linux64/bin/nvim /usr/local/bin/nvim

	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
	#nvm install 21

	wget https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tgz
	tar -xvf Python-3.12.3.tgz

	#sudo add-apt-repository ppa:deadsnakes/ppa
	#sudo apt-get update
	#sudo apt-get install python3.12

	ln -s ~/dotfiles/.zprofile ~/.zprofile
	ln -s ~/dotfiles/.zshrc ~/.zshrc
	ln -s ~/dotfiles/.zsh ~/.zsh

	mkdir ~/.config
	ln -s ~/dotfiles/.config/nvim ~/.config/nvim

	ln -s ~/dotfiles/.config/btop ~/.config/btop
	ln -s ~/dotfiles/.config/htop ~/.config/htop
	ln -s ~/dotfiles/.config/iterm2 ~/.config/iterm2
	ln -s ~/dotfiles/.config/raycast ~/.config/raycast
	ln -s ~/dotfiles/.config/wireshark ~/.config/wireshark
	ln -s ~/dotfiles/.config/karabiner ~/.config/karabiner

	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
